# This is a basic workflow to help you get started with Actions

name: CI (FHIR Validation)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validation"
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install .NET runtime
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x

      # Test SDK version
      - name: Check .NET SDK Version
        run: |
          dotnet --version
          
      # Install Firely Terminal
      - name: Install Firely Terminal
        run: |
          dotnet tool install -g firely.terminal
      
      # Test Firely Terminal install
      - name: Check Firely Terminal Version
        run: |
          fhir -v
          
      # Add resources for validation to the stack
      - name: Add resources to the Firely Terminal stack
        env:
          folders: ressourcen-profile terminologie beispiele logical-models
        run: |
          for folder in $folders; 
          do 
            echo Pushing "$folder" folder to the stack;
            cd $GITHUB_WORKSPACE/$folder
            fhir push .
          done
